name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      # Build for different platforms based on the OS
      - name: Build Electron App
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            bun run electron-builder --linux
          elif [ "$RUNNER_OS" == "Windows" ]; then
            bun run electron-builder --win
          else
            bun run electron-builder --mac
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: |
            dist/
            release/
