name: Build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      # Cache configuration with corrected OS naming
      - name: Cache Electron
        uses: actions/cache@v3
        with:
          path: |
            ${{ runner.temp }}/electron
            ${{ runner.temp }}/electron-builder
          key: ${{ runner.os }}-electron-cache-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-electron-cache-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build Application
        run: bun run build

      # Modified build command to use cross-platform syntax
      - name: Build Electron App
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            bun run electron-builder --linux
          elif [ "$RUNNER_OS" == "Windows" ]; then
            bun run electron-builder --win
          else
            bun run electron-builder --mac --x64 --arm64
          fi
        shell: bash

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}
          path: |
            dist/
            release/
